### ISSUE TITLE
ANFS episodes need replacement or serious rework

### ISSUE THREAD

**Issue by rennelu** [x-cord/conan#11]
Episodes TL'ed by ANFS (406-408, 448, 450, 451) have several mistakes. In addition to grammatical errors there seem to be several lines in each episode that omit or incorrectly translate information.

**Comment by po5** [comment]
Affected episodes (`rg 'Source: .*ANFS.*' | natsort | sed 's/:.*//' | uniq`)
0001-0999/0406.ass
0001-0999/0407.ass
0001-0999/0408.ass
0001-0999/0448.ass
0001-0999/0450.ass
0001-0999/0451.ass

**Comment by po5** [comment]
Will focus on 448, 450-451 for now since filler eps are less likely to get resubbed by other groups.
448 is truly awful.

**Comment by po5** [comment]
450-451 has been overhauled (and also since released independently by sarachikorita), 448 got a new TL.
