### ISSUE TITLE
Missing Character in Dialogue font

### ISSUE THREAD

**Issue by SkinnerK** [x-cord/conan#3]
Apparently the character ō (eg. Kaitō, Doitō) used in episodes 132 and 133 in particular is missing from the Dialogue font.
Approaches that come to mind:
Change the font
or 
replace every ō with an o
The first is the easiest, the second should be considered if you wanna standardized all the subs.
Thank you in advance.

**Comment by po5** [comment]
The goal is to eventually replace all such instances (Kaito, Kaitou, Kaitō) with a single consistent romanization.
I do want to avoid macrons, so that won't be a problem soonTM.

**Comment by SkinnerK** [comment]
Great!
Also, I am trying to contribute. But since I can't push my contributions, I forked the Repository. Hope that saves you some fixes/time.

**Comment by po5** [comment]
I appreciate your contributions. Feel free to make pull requests for any changes you want to make, I'll look over them.
Currently splitting two-parters and using UTB lines for recaps.
